# Generated by Django 3.0.6 on 2020-06-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('availability', models.BooleanField()),
                ('availabilityDuration', models.DurationField()),
                ('rentability', models.BooleanField()),
                ('used', models.BooleanField()),
                ('description', models.TextField(max_length=100)),
                ('sellPrice', models.IntegerField()),
                ('rentPerDay', models.IntegerField()),
                ('rentPerWeek', models.IntegerField()),
                ('rentPerMonth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('adress', models.CharField(max_length=30)),
                ('idImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.RentUser')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sellPrice', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('availability', models.BooleanField()),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.branches')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.branches'),
        ),
    ]
