# Generated by Django 3.0.8 on 2020-07-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product', models.CharField(max_length=30)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('adminName', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='RentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField(auto_now=True)),
                ('ends', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('adminName', models.CharField(max_length=20)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Noterecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('note', models.TextField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='FixRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=100)),
                ('adminName', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User')),
            ],
        ),
    ]
