# Generated by Django 3.0.6 on 2020-06-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('notes', models.TextField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.Bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='SellARecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('notes', models.TextField()),
                ('accessorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.accessories')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='RentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Noterecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('note', models.TextField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='FixRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User')),
            ],
        ),
    ]
