# Generated by Django 3.0.8 on 2020-07-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrecords',
            name='status',
            field=models.BooleanField(),
        ),
    ]
