# Generated by Django 3.0.8 on 2020-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sellPrice', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('availability', models.BooleanField()),
                ('branche', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('availability', models.BooleanField()),
                ('rentability', models.BooleanField()),
                ('availabilityDuration', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('sellPrice', models.IntegerField()),
                ('rentPerDay', models.IntegerField()),
                ('rentPerWeek', models.IntegerField()),
                ('rentPerMonth', models.IntegerField()),
                ('branche', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
