# Generated by Django 3.0.7 on 2020-06-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('availability', models.BooleanField()),
                ('rentability', models.BooleanField()),
                ('availabilityDuration', models.DurationField()),
                ('description', models.TextField(max_length=100)),
                ('sellPrice', models.IntegerField()),
                ('rentPerDay', models.IntegerField()),
                ('rentPerWeek', models.IntegerField()),
                ('rentPerMonth', models.IntegerField()),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.branches')),
            ],
        ),
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sellPrice', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('availability', models.BooleanField()),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.branches')),
            ],
        ),
    ]
