# Generated by Django 3.0.3 on 2020-07-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_bikeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeimage',
            name='Bike',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.Bike'),
        ),
    ]
